### ISSUE TITLE
how long does it take on laptop?

### ISSUE THREAD

**Issue by totuta** [kevinzakka/style_transfer#3]
Hi, thanks for helping me with the backend problem. Now it works. BTW, it takes forever on my laptop. How long does it usually take? On laptop and big linux machine with GPU?

**Comment by kevinzakka** [comment]
On my macbook pro 2013, it takes approximately ~130 seconds for 1 iteration which is super slow, not to mention that the computer starts going crazy and heating up - definitely not recommended. 

I tried it on a Geoforce Titan X and it took about 1.5-3 seconds per iteration which is a huge improvement.

Also note that the width parameter directly affects computation speed. If you execute say `--width=100`, it should speed up the iterations by a huge factor. The bigger the image, the longer it takes.
